server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://dreamli:369254@peer1:10086/eureka,http://dreamli:369254@peer2:10087/eureka,http://dreamli:369254@peer3:10088/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
    ip-address: 127.0.0.1

#spring:
#  elasticsearch:
#    rest:
#      uris: http://127.0.0.1:9200
##      username:
##      password:
#      read-timeout: 10
#      connection-timeout: 2

# es
spring:
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout: 30
          use-ssl: false
#          endpoints:
#          username:
#          password:
      cluster-nodes: 127.0.0.1:9200
      cluster-name: elasticsearch
      repositories:
        enabled: true
